# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 01132414f1290c53ffd76efcd44c135d09b399d318f80a8eb3fe9f775878e0695522b17c9c02da487070a5fd44a7274ca851d72cb63d85859851b9d3bdc8aa7b

test:
  secret_key_base: 700c6fcd18233a4629f38a4f85f1240bf466e7912cfad298db05ce4863e49ec14ef5f977c0c7d36fc74c4a866bef6e05fca6ccd91a75b600450e2eae1f97779e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
